-- Superseded by setup_daily_cron.sql. The database cron is required because
-- the GitHub Actions schedule stopped firing in February 2026. Do not remove
-- generate-daily-palette from cron.job when applying this repository.
