-- Retired. The GitHub Actions workflow generates palettes at 9 AM Pacific
-- with separate 16:00 and 17:00 UTC invocations and a Pacific-time guard in
-- the Edge Function. Do not reinstall the legacy fixed-17-UTC database cron.
-- For existing installations, run retire_legacy_palette_cron.sql.
